name: publish
on: 
  push:
    branches:
      - main
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build the cribl-plus Docker image
        run: |
          docker build . --tag ghcr.io/pdugas/cribl-plus:latest
          docker push ghcr.io/pdugas/cribl-plus:latest
