name: publish
on: 
  push:
    branches:
      - main
  schedule:
    # update it weekly, Sundays at midnight
    - cron: '0 0 * * 0'
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build the cribl-plus Docker image
        run: |
          docker build . --tag ghcr.io/pdugas/cribl-plus:latest --pull
          docker push ghcr.io/pdugas/cribl-plus:latest
